---
- name: Deploy Scientific Calculator Application
  hosts: localhost
  become: no
  vars:
    docker_image: "srinivas1405/scientific-calculator:latest"
    container_name: "scientific-calculator"
    
  tasks:
    - name: Stop and remove existing container
      shell: docker stop {{ container_name }} && docker rm {{ container_name }}
      ignore_errors: yes
      
    - name: Pull latest image
      shell: docker pull {{ docker_image }}
      
    - name: Run container
      shell: docker run -d --name {{ container_name }} {{ docker_image }}
      
    - name: Show running containers
      shell: docker ps
      register: containers
      
    - name: Display containers
      debug:
        var: containers.stdout_lines
