---
- name: Deploy Scientific Calculator Application
  hosts: localhost
  become: yes
  vars:
    docker_image: "srinivas1405/scientific-calculator:latest"
    container_name: "scientific-calculator"
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: yes
      
    - name: Install Docker (if not installed)
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      when: docker_check.rc != 0
      
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Stop existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes
      
    - name: Remove old image
      docker_image:
        name: "{{ docker_image }}"
        state: absent
        force_absent: yes
      ignore_errors: yes
      
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        
    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: unless-stopped
        interactive: yes
        tty: yes
        detached: no
        
    - name: Display container status
      command: docker ps -a
      register: container_status
      
    - name: Show container status
      debug:
        var: container_status.stdout_lines
